directory: ~/Music
plugins: scrub zero info fetchart embedart lastgenre ftintitle
duplicate_action: ask
asciify_paths: yes
original_date: yes
zero:
  keep_fields: title artist album year track genre images
ftintitle:
  drop: no
  auto: yes
import:
  timid: no
  move: yes
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '^-': _
    '[\&]': 'and'
    '[\(\)\[\]\!]': ''
