directory: ~/Music
plugins: info fetchart embedart lastgenre ftintitle zero scrub missing
duplicate_action: ask
asciify_paths: yes
original_date: yes
lastgenre:
  source: artist
  force: yes
  fallback: Unknown
  canonical: ~/.config/beets/genres.yml
  whitelist: ~/.config/beets/whitelist.txt
missing:
    format: $albumartist - $album - $title
    count: no
    total: no
zero:
  keep_fields: title artist album date year track genre genres images country publisher label
embedart:
  ifempty: yes
  remove_art_file: yes
ftintitle:
  drop: no
  auto: yes
import:
  timid: no
  move: yes
  write: yes
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '^-': _
    '[\&]': 'and'
    '[\(\)\[\]\!]': ''
